const productsByCategory = {
  allProducts: [
    {
      id: 1,
      name: "Smart Watch Pro",
      description: "Advanced smartwatch with health tracking and notifications",
      price: "$199.99",
      originalPrice: "$249.99",
      discount: "-20%",
      image: "/src/assets/watch.png",
      rating: 4.5,
      orders: "500+",
      shipping: "Free shipping",
      dateAdded: "2023-05-15"
    },
    {
      id: 2,
      name: "Ultra Slim Laptop",
      description: "Lightweight laptop with 16GB RAM and 512GB SSD",
      price: "$899.99",
      image: "/src/assets/laptop.png",
      rating: 4.8,
      orders: "1200+",
      shipping: "Free shipping",
      dateAdded: "2023-06-20"
    },
    {
      id: 3,
      name: "4K Action Camera",
      description: "Waterproof camera with 4K video and image stabilization",
      price: "$299.99",
      originalPrice: "$349.99",
      discount: "-14%",
      image: "/src/assets/camera.png",
      rating: 4.7,
      orders: "800+",
      shipping: "Free shipping",
      dateAdded: "2023-07-10"
    },
    {
      id: 4,
      name: "Noise Cancelling Headphones",
      description: "Wireless headphones with 30-hour battery life",
      price: "$179.99",
      image: "/src/assets/ear-fone.png",
      rating: 4.6,
      orders: "1500+",
      shipping: "Free shipping",
      dateAdded: "2023-04-05"
    },
    {
      id: 5,
      name: "DSLR Camera Bundle",
      description: "Professional camera with 24.2MP sensor and lens kit",
      price: "$799.99",
      image: "/src/assets/black-fone.png",
      rating: 4.9,
      orders: "600+",
      shipping: "$5.99 shipping",
      dateAdded: "2023-08-12"
    },
    {
      id: 6,
      name: "Ergonomic Office Chair",
      description: "Comfortable chair with lumbar support and adjustable height",
      price: "$249.99",
      originalPrice: "$299.99",
      discount: "-17%",
      image: "/src/assets/sofa.png",
      rating: 4.4,
      orders: "900+",
      shipping: "$9.99 shipping",
      dateAdded: "2023-03-18"
    },
    {
      id: 7,
      name: "Modern Desk Lamp",
      description: "LED lamp with adjustable brightness and color temperature",
      price: "$49.99",
      image: "/src/assets/lamp.png",
      rating: 4.3,
      orders: "2000+",
      shipping: "Free shipping",
      dateAdded: "2023-02-22"
    },
    {
      id: 8,
      name: "Ceramic Dinner Set",
      description: "12-piece ceramic dinnerware set, dishwasher safe",
      price: "$89.99",
      image: "/src/assets/box.png",
      rating: 4.5,
      orders: "700+",
      shipping: "Free shipping",
      dateAdded: "2023-09-05"
    },
    {
      id: 9,
      name: "Premium Blender",
      description: "High-speed blender with 1500W motor and 8 presets",
      price: "$129.99",
      originalPrice: "$159.99",
      discount: "-19%",
      image: "/src/assets/blender.png",
      rating: 4.7,
      orders: "1100+",
      shipping: "Free shipping",
      dateAdded: "2023-01-15"
    },
    {
      id: 10,
      name: "Wireless Charging Pad",
      description: "Fast-charging Qi-enabled pad for all compatible devices",
      price: "$29.99",
      image: "/src/assets/wallet.png",
      rating: 4.2,
      orders: "2500+",
      shipping: "Free shipping",
      dateAdded: "2023-10-08"
    },
    {
      id: 11,
      name: "Gaming Headset Pro",
      description: "Surround sound gaming headset with noise-cancelling mic",
      price: "$99.99",
      image: "/src/assets/white-ear-fone.png",
      rating: 4.6,
      orders: "1300+",
      shipping: "Free shipping",
      dateAdded: "2023-11-11"
    },
    {
      id: 12,
      name: "Smartphone Tripod",
      description: "Adjustable tripod with remote shutter for smartphones",
      price: "$24.99",
      image: "/src/assets/kettle.png",
      rating: 4.1,
      orders: "1800+",
      shipping: "$4.99 shipping",
      dateAdded: "2023-07-30"
    },
    {
      id: 13,
      name: "Men's Casual T-Shirt",
      description: "100% cotton t-shirt available in multiple colors",
      price: "$19.99",
      originalPrice: "$24.99",
      discount: "-20%",
      image: "/src/assets/blue-shirt.png",
      rating: 4.3,
      orders: "3000+",
      shipping: "Free shipping",
      dateAdded: "2023-04-17"
    },
    {
      id: 14,
      name: "Leather Wallet",
      description: "Genuine leather wallet with multiple card slots",
      price: "$39.99",
      image: "/src/assets/blue-wallet.png",
      rating: 4.4,
      orders: "1600+",
      shipping: "Free shipping",
      dateAdded: "2023-08-25"
    },
    {
      id: 15,
      name: "Travel Backpack",
      description: "Water-resistant backpack with USB charging port",
      price: "$59.99",
      image: "/src/assets/blue-bag.png",
      rating: 4.7,
      orders: "1400+",
      shipping: "Free shipping",
      dateAdded: "2023-05-30"
    }
  ],

  deals: [
    {
      id: 1,
      name: "Smart Watch Pro",
      description: "Limited time deal on our best-selling smartwatch",
      price: "$179.99",
      originalPrice: "$249.99",
      discount: "-28%",
      image: "/src/assets/watch.png",
      rating: 4.5,
      orders: "500+",
      shipping: "Free shipping",
      dateAdded: "2023-05-15"
    },
    {
      id: 2,
      name: "Ultra Slim Laptop",
      description: "Special discount on this high-performance laptop",
      price: "$849.99",
      originalPrice: "$999.99",
      discount: "-15%",
      image: "/src/assets/laptop.png",
      rating: 4.8,
      orders: "1200+",
      shipping: "Free shipping",
      dateAdded: "2023-06-20"
    },
    {
      id: 3,
      name: "4K Action Camera",
      description: "Flash sale on this professional action camera",
      price: "$279.99",
      originalPrice: "$349.99",
      discount: "-20%",
      image: "/src/assets/camera.png",
      rating: 4.7,
      orders: "800+",
      shipping: "Free shipping",
      dateAdded: "2023-07-10"
    },
    {
      id: 4,
      name: "Noise Cancelling Headphones",
      description: "Limited stock at this discounted price",
      price: "$159.99",
      originalPrice: "$199.99",
      discount: "-20%",
      image: "/src/assets/ear-fone.png",
      rating: 4.6,
      orders: "1500+",
      shipping: "Free shipping",
      dateAdded: "2023-04-05"
    },
    {
      id: 5,
      name: "DSLR Camera Bundle",
      description: "Bundle deal with extra lens included",
      price: "$749.99",
      originalPrice: "$899.99",
      discount: "-17%",
      image: "/src/assets/black-fone.png",
      rating: 4.9,
      orders: "600+",
      shipping: "Free shipping",
      dateAdded: "2023-08-12"
    }
  ],

  homeAndOutdoor: [
    {
      id: 1,
      name: "Ergonomic Office Chair",
      description: "Comfortable chair with lumbar support",
      price: "$249.99",
      originalPrice: "$299.99",
      discount: "-17%",
      image: "/src/assets/sofa.png",
      rating: 4.4,
      orders: "900+",
      shipping: "$9.99 shipping",
      dateAdded: "2023-03-18"
    },
    {
      id: 2,
      name: "Modern Desk Lamp",
      description: "LED lamp with adjustable settings",
      price: "$49.99",
      image: "/src/assets/lamp.png",
      rating: 4.3,
      orders: "2000+",
      shipping: "Free shipping",
      dateAdded: "2023-02-22"
    },
    {
      id: 3,
      name: "Ceramic Dinner Set",
      description: "12-piece dinnerware set",
      price: "$89.99",
      image: "/src/assets/box.png",
      rating: 4.5,
      orders: "700+",
      shipping: "Free shipping",
      dateAdded: "2023-09-05"
    },
    {
      id: 4,
      name: "Indoor Plant Set",
      description: "Set of 3 low-maintenance house plants",
      price: "$39.99",
      image: "/src/assets/mud.png",
      rating: 4.6,
      orders: "1100+",
      shipping: "$7.99 shipping",
      dateAdded: "2023-10-15"
    },
    {
      id: 5,
      name: "Premium Blender",
      description: "High-speed kitchen blender",
      price: "$129.99",
      originalPrice: "$159.99",
      discount: "-19%",
      image: "/src/assets/blender.png",
      rating: 4.7,
      orders: "1100+",
      shipping: "Free shipping",
      dateAdded: "2023-01-15"
    },
    {
      id: 6,
      name: "Coffee Maker",
      description: "Programmable 12-cup coffee maker",
      price: "$79.99",
      image: "/src/assets/cactus.png",
      rating: 4.5,
      orders: "1600+",
      shipping: "Free shipping",
      dateAdded: "2023-07-22"
    },
    {
      id: 7,
      name: "Air Fryer Oven",
      description: "Multi-function air fryer and oven combo",
      price: "$149.99",
      originalPrice: "$179.99",
      discount: "-17%",
      image: "/src/assets/mixer.png",
      rating: 4.8,
      orders: "900+",
      shipping: "Free shipping",
      dateAdded: "2023-11-05"
    },
    {
      id: 8,
      name: "Outdoor Patio Set",
      description: "4-piece weather-resistant patio furniture",
      price: "$399.99",
      image: "/src/assets/tablet.png",
      rating: 4.4,
      orders: "400+",
      shipping: "$19.99 shipping",
      dateAdded: "2023-04-30"
    }
  ],

  electronics: [
    {
      id: 1,
      name: "Smart Watch Pro",
      description: "Advanced smartwatch with health tracking",
      price: "$199.99",
      originalPrice: "$249.99",
      discount: "-20%",
      image: "/src/assets/watch.png",
      rating: 4.5,
      orders: "500+",
      shipping: "Free shipping",
      dateAdded: "2023-05-15"
    },
    {
      id: 2,
      name: "Ultra Slim Laptop",
      description: "Lightweight laptop with 16GB RAM",
      price: "$899.99",
      image: "/src/assets/laptop.png",
      rating: 4.8,
      orders: "1200+",
      shipping: "Free shipping",
      dateAdded: "2023-06-20"
    },
    {
      id: 3,
      name: "4K Action Camera",
      description: "Waterproof camera with 4K video",
      price: "$299.99",
      originalPrice: "$349.99",
      discount: "-14%",
      image: "/src/assets/camera.png",
      rating: 4.7,
      orders: "800+",
      shipping: "Free shipping",
      dateAdded: "2023-07-10"
    },
    {
      id: 4,
      name: "Noise Cancelling Headphones",
      description: "Wireless headphones with 30-hour battery",
      price: "$179.99",
      image: "/src/assets/ear-fone.png",
      rating: 4.6,
      orders: "1500+",
      shipping: "Free shipping",
      dateAdded: "2023-04-05"
    },
    {
      id: 5,
      name: "Gaming Console",
      description: "Next-gen gaming console with 1TB storage",
      price: "$499.99",
      image: "/src/assets/black-fone.png",
      rating: 4.9,
      orders: "2000+",
      shipping: "Free shipping",
      dateAdded: "2023-09-15"
    },
    {
      id: 6,
      name: "Wireless Earbuds",
      description: "True wireless earbuds with charging case",
      price: "$129.99",
      originalPrice: "$149.99",
      discount: "-13%",
      image: "/src/assets/white-ear-fone.png",
      rating: 4.4,
      orders: "1800+",
      shipping: "Free shipping",
      dateAdded: "2023-08-10"
    },
    {
      id: 7,
      name: "Smartphone Gimbal",
      description: "3-axis stabilizer for smartphone videography",
      price: "$99.99",
      image: "/src/assets/red-fone.png",
      rating: 4.5,
      orders: "700+",
      shipping: "Free shipping",
      dateAdded: "2023-10-20"
    },
    {
      id: 8,
      name: "Portable SSD",
      description: "1TB ultra-fast portable solid state drive",
      price: "$129.99",
      originalPrice: "$159.99",
      discount: "-19%",
      image: "/src/assets/kettle.png",
      rating: 4.7,
      orders: "1100+",
      shipping: "Free shipping",
      dateAdded: "2023-07-05"
    }
  ],

  recommended: [
    {
      id: 1,
      name: "Men's Casual T-Shirt",
      description: "100% cotton t-shirt in multiple colors",
      price: "$19.99",
      originalPrice: "$24.99",
      discount: "-20%",
      image: "/src/assets/blue-shirt.png",
      rating: 4.3,
      orders: "3000+",
      shipping: "Free shipping",
      dateAdded: "2023-04-17"
    },
    {
      id: 2,
      name: "Leather Wallet",
      description: "Genuine leather wallet with RFID protection",
      price: "$39.99",
      image: "/src/assets/blue-wallet.png",
      rating: 4.4,
      orders: "1600+",
      shipping: "Free shipping",
      dateAdded: "2023-08-25"
    },
    {
      id: 3,
      name: "Travel Backpack",
      description: "Water-resistant backpack with USB port",
      price: "$59.99",
      image: "/src/assets/blue-bag.png",
      rating: 4.7,
      orders: "1400+",
      shipping: "Free shipping",
      dateAdded: "2023-05-30"
    },
    {
      id: 4,
      name: "Men's Jeans Shorts",
      description: "Comfortable denim shorts for summer",
      price: "$29.99",
      originalPrice: "$39.99",
      discount: "-25%",
      image: "/src/assets/jeans-short.png",
      rating: 4.2,
      orders: "1900+",
      shipping: "Free shipping",
      dateAdded: "2023-06-12"
    },
    {
      id: 5,
      name: "Winter Coat",
      description: "Warm insulated coat for cold weather",
      price: "$129.99",
      image: "/src/assets/brown-jacket.png",
      rating: 4.6,
      orders: "800+",
      shipping: "Free shipping",
      dateAdded: "2023-11-01"
    },
    {
      id: 6,
      name: "Smart Watch Pro",
      description: "Our best-selling smartwatch",
      price: "$199.99",
      originalPrice: "$249.99",
      discount: "-20%",
      image: "/src/assets/watch.png",
      rating: 4.5,
      orders: "500+",
      shipping: "Free shipping",
      dateAdded: "2023-05-15"
    },
    {
      id: 7,
      name: "Noise Cancelling Headphones",
      description: "Premium wireless headphones",
      price: "$179.99",
      image: "/src/assets/ear-fone.png",
      rating: 4.6,
      orders: "1500+",
      shipping: "Free shipping",
      dateAdded: "2023-04-05"
    },
    {
      id: 8,
      name: "Ceramic Dinner Set",
      description: "Elegant 12-piece dinnerware set",
      price: "$89.99",
      image: "/src/assets/box.png",
      rating: 4.5,
      orders: "700+",
      shipping: "Free shipping",
      dateAdded: "2023-09-05"
    },
    {
      id: 9,
      name: "Premium Blender",
      description: "High-performance kitchen blender",
      price: "$129.99",
      originalPrice: "$159.99",
      discount: "-19%",
      image: "/src/assets/blender.png",
      rating: 4.7,
      orders: "1100+",
      shipping: "Free shipping",
      dateAdded: "2023-01-15"
    },
    {
      id: 10,
      name: "Travel Backpack",
      description: "Durable backpack for travelers",
      price: "$59.99",
      image: "/src/assets/blue-bag.png",
      rating: 4.7,
      orders: "1400+",
      shipping: "Free shipping",
      dateAdded: "2023-05-30"
    }
  ]
};

export default productsByCategory;